config/routes.rb
Rails.application.routes.draw do
  resources :racers do
    post "entries" => "racers#create_entry"
  end
  resources :races

  namespace :api do
    resources :racers do
      resources :entries
    end
    resources :races do
      resources :results
    end
  end

end

app/models/race.rb
class Race
  include Mongoid::Document
  include Mongoid::Timestamps::Updated
  include Mongoid::Timestamps::Created

  field :n, as: :name, type: String
  field :date, type: Date
  field :loc, as: :location , type: Address
  field :next_bib, type: Integer, default: 0


  embeds_many :events, as: 'parent', order: [:order.asc]
  has_many :entrants, foreign_key: "race._id", dependent: :delete, order: [:secs.asc, :bib.asc]

  scope :past, ->{ where(:date => { :$lt => Date.today }) }
  scope :upcoming, ->{ where(:date => { :$gte => Date.today }) }

  def self.upcoming_available_to racer
    upcoming_race_ids = racer.races.upcoming.pluck(:race).map {|r| r[:_id]}
    Race.upcoming.where(:_id=> {:$nin => upcoming_race_ids})
  end

  DEFAULT_EVENTS = {"swim"=>{:order=>0, :name=>"swim", :distance=>1.0, :units=>"miles"},
                    "t1"=>  {:order=>1, :name=>"t1"},
                    "bike"=>{:order=>2, :name=>"bike", :distance=>25.0, :units=>"miles"},
                    "t2"=>  {:order=>3, :name=>"t2"},
                    "run"=> {:order=>4, :name=>"run", :distance=>10.0, :units=>"kilometers"}}

  DEFAULT_EVENTS.keys.each do |name|
    define_method("#{name}") do
      event=events.select {|event| name==event.name}.first
      event||=events.build(DEFAULT_EVENTS["#{name}"])
    end
    ["order","distance","units"].each do |prop|
      if DEFAULT_EVENTS["#{name}"][prop.to_sym]
        define_method("#{name}_#{prop}") do
          event=self.send("#{name}").send("#{prop}")
        end
        define_method("#{name}_#{prop}=") do |value|
          event=self.send("#{name}").send("#{prop}=", value)
        end
      end
    end
  end

  ["city", "state"].each do |action|
    define_method("#{action}") do
      self.location ? self.location.send("#{action}") : nil
    end
    define_method("#{action}=") do |name|
      object=self.location ||= Address.new
      object.send("#{action}=", name)
      self.location=object
    end
  end

  def self.default
    Race.new do |race|
      DEFAULT_EVENTS.keys.each {|leg|race.send("#{leg}")}
    end
  end

  def next_bib
    self.inc(next_bib: 1)
    self[:next_bib]
  end

  def get_group racer
    if racer && racer.birth_year && racer.gender
      quotient=(date.year-racer.birth_year)/10
      min_age=quotient*10
      max_age=((quotient+1)*10)-1
      gender=racer.gender
      name=min_age >= 60 ? "masters #{gender}" : "#{min_age} to #{max_age} (#{gender})"
      Placing.demongoize(:name=>name)
    end
  end

  def create_entrant racer
    if racer
      entrant = Entrant.new
      entrant.race = self.attributes.symbolize_keys.slice(:_id, :n, :date)
      entrant.racer = racer.info.attributes
      entrant.group = self.get_group(racer)
      #self.entrants << entrant
      self.events.to_a.each do |event|
        entrant.send("#{event.name}=", event)
      end
      if entrant.validate
        entrant.bib = self.next_bib
        entrant.save
      end
      entrant
    end
  end
end

app/controllers/api/races_controller.rb
module Api
  class RacesController < ApplicationController

    rescue_from Mongoid::Errors::DocumentNotFound do |exception|
      if !request.accept || request.accept == "*/*"
        render plain: "woops: cannot find race[#{params[:id]}]", status: :not_found
      else
        render :status=>:not_found,
               :template=>"api/error_msg",
               :locals=>{ :msg=>"woops: cannot find race[#{params[:id]}]"}
      end
    end

    rescue_from ActionView::MissingTemplate do |exception|
      Rails.logger.debug exception
      render plain: "woops: we do not support that content-type[#{request.accept}]", status: :unsupported_media_type
    end

    # GET /races
    # GET /races.json
    def index
      if !request.accept || request.accept == "*/*"
        render plain: "/api/races, offset=[#{params[:offset]}], limit=[#{params[:limit]}]"
      else
        #real implementation ...
      end
    end

    # GET /races/1
    # GET /races/1.json
    def show
      if !request.accept || request.accept == "*/*"
        render plain: "/api/races/#{params[:id]}"
      else
        @race = Race.find(params[:id])
        #render json: @race, status: :ok
        render @race, status: :ok
      end
    end

    def show_result
      if !request.accept || request.accept == "*/*"
        render plain: "/api/races/#{params[:race_id]}/results/#{params[:id]}"
      else
        #real implementation ...
        @result=Race.find(params[:race_id]).entrants.where(:id=>params[:id]).first
        render :partial=>"result", :object=>@result
      end
    end

    def show_results
      if !request.accept || request.accept == "*/*"
        render plain: "/api/races/#{params[:race_id]}/results"
      else
        #real implementation ...
        @race=Race.find(params[:race_id])
        if stale?(@race)
          @entrants=@race.entrants
          render template: "api/results/index"
        end
      end
    end

    def update_result
      result=params[:result]
      entrant=Race.find(params[:race_id]).entrants.where(:id=>params[:id]).first
      if result
        if result[:swim]
          entrant.swim=entrant.race.race.swim
          entrant.swim_secs = result[:swim].to_f
        end
        if result[:t1]
          entrant.t1=entrant.race.race.t1
          entrant.t1_secs = result[:t1].to_f
        end
        if result[:bike]
          entrant.bike=entrant.race.race.bike
          entrant.bike_secs = result[:bike].to_f
        end
        if result[:t2]
          entrant.t2=entrant.race.race.t2
          entrant.t2_secs = result[:t2].to_f
        end
        if result[:run]
          entrant.run=entrant.race.race.run
          entrant.run_secs = result[:run].to_f
        end
        entrant.save
      end
      if !request.accept || request.accept == "*/*"
        render plain: "/api/races/#{params[:race_id]}/results/#{params[:id]}"
      else
        #real implementation ...
        @result = entrant
        render :partial=>"result", :object=>@result
      end
    end

    # GET /races/new
    def new
    end

    # GET /races/1/edit
    def edit
    end

    # POST /races
    # POST /races.json
    def create
      #render plain: :nothing, status: :ok
      if !request.accept || request.accept == "*/*"
        if params[:race]
          render plain: params[:race][:name], status: :ok
        else
          render plain: :nothing, status: :ok
        end
      else
        race_hash = race_params
        @race = Race.new(race_hash)
        @race.save
        render plain: @race.name, status: :created, content_type: 'text/plain'
      end
    end

    # PATCH/PUT /races/1
    # PATCH/PUT /races/1.json
    def update
      @race = Race.find(params[:id])
      if @race.update(race_params)
        render json: @race, status: :ok
      else
        render json: @race, status: :unprocessable_entity
      end
    end

    # DELETE /races/1
    # DELETE /races/1.json
    def destroy
      @race = Race.find(params[:id])
      @race.destroy
      render :nothing=>true, :status => :no_content
    end

    private

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :date)
    end

  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    #@races = Race.all
    @races = Race.all.order_by(:created_at => 'desc')
  end

  # GET /races/1
  # GET /races/1.json
  def show
    set_race()
    if @race
      @entrants=Entrant.where(:"race._id"=>@race.id).order_by(:secs => 'asc', :last_name => 'asc', :first_name => 'asc')
    else
      @entrants=[]
    end
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_race
    @race = Race.find(params[:id])
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :date, :city, :state, :swim_distance, :swim_units, :bike_distance, :bike_units, :run_distance, :run_units)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :swim_distance %><br>
    <%= f.text_field :swim_distance %>
  </div>
  <div class="field">
    <%= f.label :swim_units %><br>
    <%= f.text_field :swim_units %>
  </div>
  <div class="field">
    <%= f.label :bike_distance %><br>
    <%= f.text_field :bike_distance %>
  </div>
  <div class="field">
    <%= f.label :bike_units %><br>
    <%= f.text_field :bike_units %>
  </div>
  <div class="field">
    <%= f.label :run_distance %><br>
    <%= f.text_field :run_distance %>
  </div>
  <div class="field">
    <%= f.label :run_units %><br>
    <%= f.text_field :run_units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Races</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>City</th>
      <th>State</th>
      <th>Swim distance</th>
      <th>Swim units</th>
      <th>Bike distance</th>
      <th>Bike units</th>
      <th>Run distance</th>
      <th>Run units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= race.date %></td>
        <td><%= race.city %></td>
        <td><%= race.state %></td>
        <td><%= race.swim_distance %></td>
        <td><%= race.swim_units %></td>
        <td><%= race.bike_distance %></td>
        <td><%= race.bike_units %></td>
        <td><%= race.run_distance %></td>
        <td><%= race.run_units %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @race.date %>
</p>

<p>
  <strong>City:</strong>
  <%= @race.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @race.state %>
</p>

<p>
  <strong>Swim distance:</strong>
  <%= @race.swim_distance %>
</p>

<p>
  <strong>Swim units:</strong>
  <%= @race.swim_units %>
</p>

<p>
  <strong>Bike distance:</strong>
  <%= @race.bike_distance %>
</p>

<p>
  <strong>Bike units:</strong>
  <%= @race.bike_units %>
</p>

<p>
  <strong>Run distance:</strong>
  <%= @race.run_distance %>
</p>

<p>
  <strong>Run units:</strong>
  <%= @race.run_units %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>

</p><strong>Results:</strong>
<table>
  <thead>
  <tr>
    <th>Place</th>
    <th>Time</th>
    <th>Name</th>
    <th>Bib#</th>
    <th>City</th>
    <th>State</th>
    <th>Gender</th>
    <th>Gender Place</th>
    <th>Group</th>
    <th>Group Place</th>
    <th>Swim</th>
    <th>Pace 100</th>
    <th>T1</th>
    <th>Bike</th>
    <th>MPH</th>
    <th>T2</th>
    <th>Run</th>
    <th>Min Mile</th>
  </tr>
  </thead>

  <tbody>
  <% @entrants.each do |entrant| %>
      <tr>
        <td><%= entrant.overall_place %></td>
        <td><%= format_hours entrant.secs %></td>
        <% if entrant.racer.id %>
            <td><%= link_to "#{entrant.last_name}, #{entrant.first_name}", racer_path(entrant.racer.id) %></td>
        <% else %>
            <td><%= "#{entrant.last_name}, #{entrant.first_name}" %></td>
        <% end %>
        <td><%= entrant.bib %></td>
        <td><%= entrant.city %></td>
        <td><%= entrant.state %></td>
        <td><%= entrant.racer_gender %></td>
        <td><%= entrant.gender_place %></td>
        <td><%= entrant.group.name %></td>
        <td><%= entrant.group_place %></td>
        <td><%= format_hours entrant.swim_secs %></td>
        <td><%= format_minutes entrant.swim_pace_100 %></td>
        <td><%= format_minutes entrant.t1_secs %></td>
        <td><%= format_hours entrant.bike_secs %></td>
        <td><%= format_mph  entrant.bike_mph %></td>
        <td><%= format_minutes entrant.t2_secs %></td>
        <td><%= format_hours entrant.run_secs %></td>
        <td><%= format_minutes entrant.run_mmile %></td>
      </tr>
  <% end %>
  </tbody>
</table>